export const INGREDIENTS: string[] = [
  "Salt",
  "Pepper",
  "Olive oil",
  "Garlic",
  "Onion",
  "Butter",
  "Flour",
  "Eggs",
  "Milk",
  "Sugar",
  "Tomatoes",
  "Lemon",
  "Vinegar",
  "Soy sauce",
  "Ginger",
  "Cumin",
  "Paprika",
  "Chili powder",
  "Oregano",
  "Basil",
  "Rosemary",
  "Thyme",
  "Bay leaves",
  "Coriander",
  "Turmeric",
  "Mustard seeds",
  "Nutmeg",
  "Cinnamon",
  "Cloves",
  "Cardamom",
  "Fennel seeds",
  "Dill",
  "Parsley",
  "Chives",
  "Sage",
  "Mint",
  "Honey",
  "Maple syrup",
  "Worcestershire sauce",
  "Mayonnaise",
  "Black beans",
  "Coconut milk",
  "Cilantro",
  "Lime",
  "Green onions",
  "Jalapeño",
  "Avocado",
  "Sour cream",
  "Corn",
  "Red bell pepper",
  "Yellow bell pepper",
  "Zucchini",
  "Balsamic vinegar",
  "Hoisin sauce",
  "Fish sauce",
  "Rice vinegar",
  "Mirin",
  "Tahini",
  "Sesame oil",
  "Sriracha",
  "Quinoa",
  "Pesto",
  "Sun-dried tomatoes",
  "Artichoke hearts",
  "Pine nuts",
  "Parmesan cheese",
  "Gorgonzola cheese",
  "Feta cheese",
  "Prosciutto",
  "Salami",
  "Pancetta",
  "Chicken stock",
  "Beef stock",
  "Vegetable stock",
  "Red wine",
  "White wine",
  "Dark chocolate",
  "Mascarpone cheese",
  "Ricotta cheese",
  "Cottage cheese",
];
